#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     | Website:  https://openfoam.org
#   \\  /    A nd           | Copyright (C) 2015-2018 OpenFOAM Foundation
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     foamSequenceVTKFilesForFFarm
#
# Description
#     Creates symbolic links to all VTK files in a post-processing directory
#     Links form a sequence like name.0000.vtk, name.0001.vtk, etc.
#     Paraview recognises link names as a sequence which can be animated.
#     The sequence of links can be used to create a video from the images.
#     - Default directory name for VTK files is postProcessing
#
#     Function modified by Regis Thedin on Aug 2022 to handle FAST.Farm
#     ambient wind files. The modifications include the option to copy,
#     rather than link, the output files; as well as the renaming structure.
#     Note that the renaming can still be changed through some input variables
#
#------------------------------------------------------------------------------
error() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    usage
    exit 1
}

usage() {
        cat <<USAGE

Usage: ${0##*/} [OPTIONS] ...
options:
  -case   | -c <dir>    specify case directory (default = local dir)
  -dir    | -d <dir>    post-processing directory <dir> (default = postProcessing)
  -help   | -h          print the usage
  -out    | -o <dir>    output links directory <dir> (default = sequencedVTK)
  -format | -f <str>    format option of output files
  -mode   | -m <str>    mode of operation, ln or cp (default=ln)
  -lzero  | -lz <bool>  numbered output files contain leading zeros (default=true)

Creates symbolic links to all VTK files in a post-processing directory
Links form a sequence like name.0000.vtk, name.0001.vtk, etc.
The format can be changed to Amb.t0000.vtk, for example, by using the -f flag.
Paraview recognises the link names as a sequence which can be opened and played.
The sequence of links to images can be used to create a video from the images.
- Default directory name for VTK files is postProcessing
- Example call for processing of FAST.Farm results
  foamSequenceVTKFilesForFFarm -dir postProcessing/Low -out Low -format Amb.t 
                               -mode cp -lzero false
USAGE
}

dir=postProcessing
out=sequencedVTK
format=none
mode=ln
lzero=true

while [ "$#" -gt 0 ]
do
   case "$1" in
   -c | -case)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      cd "$2" 2>/dev/null || error "directory does not exist:  '$2'"
      shift 2
      ;;
   -d | -dir)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      dir=$2
      shift 2
      ;;
   -h | -help)
      usage && exit 0
      ;;
   -o | -out)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      out=$2
      shift 2
      ;;
   -f | -format)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      format=$2
      shift 2
      ;;
   -m | -mode)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      mode=$2
      shift 2
      ;;
   -lz| -lzero)
      [ "$#" -ge 2 ] || error "'$1' option requires an argument"
      lzero=$2
      shift 2
      ;;
   -*)
      error "invalid option '$1'"
      ;;
   *)
      break
      ;;
    esac
done

[ ! -d "$dir" ] && error "Cannot find postProcessing directory, exiting."

files=$(find "$dir" -type f -name "*vtk")
names=$(for f in $files; do basename "$f" .vtk; done | sort -u)

if [ -d "$out" ]; then
    echo "$out directory already exists.  Deleting links within it..."
    rm "${out:?}"/* 2>/dev/null
else
    echo "Creating $out directory..."
    mkdir "$out"
fi

for n in $names
do
    echo "Sequencing all VTK files named $n.vtk"

    # Create list of VTK files, ordered by time step
    file_list=$(echo "$files" | \
        tr " " "\n" | \
        grep -w "$n\.vtk" | \
        awk -F'/' '{print($(NF-1)" "$0)}' | \
        LC_ALL=C  sort -k 1 -g | \
        cut -d' ' -f2)

    i=0
    for f in $file_list
    do
        i=$(( i + 1 )) # Relies on ordered list of files
        if [[ $format == "none" ]]; then
            format=$n.
        fi

        if $lzero; then
            link=$(printf "${format}%04d.vtk" $i)
        else
            link=$(printf "${format}%d.vtk" $i)
        fi

        if [[ $mode == "cp" ]]; then
            cp    "$f" "$out/$link"
        else
            ln -s "../$f" "$out/$link"
        fi
    done
done
